on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: TTalex/AequilibraE-GUI
          path: AequilibraE-GUI
      
      - uses: actions/checkout@v3
        with:
          repository: TTalex/aequilibrae
          path: AequilibraE-GUI/aequilibrae

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: actions/checkout@v3
        with:
          repository: TTalex/qgis-plugin-ci
      # - name: Install qgis-plugin-ci
      #   run: pip3 install qgis-plugin-ci

      - name: Deploy plugin
        run: >-
          PYTHONPATH=qgis-plugin-ci qgis-plugin-ci/scripts/qgis_plugin_ci.py
          release ${GITHUB_REF/refs\/tags\//}
          --allow-uncommitted-changes
          --github-token ${{ secrets.GITHUB_TOKEN }}
